### ISSUE TITLE
Proyecto TopicosReporte1

### ISSUE THREAD

**Issue by JoseMVasquezD** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-topicosa-equiporr#4]
[reporte_1_topicos_ProyectoRR (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-topicosa-equiporr/files/10777292/reporte_1_topicos_ProyectoRR.1.pdf)

**Comment by Elisahadad** [comment]
calificación: 12.
Falta lista de figuras, complementar el desarrollo y reforzar la conclusión.

**Comment by josealfredo79** [comment]
Falta mejorar el trabajo, para la proxima se regresa el trabajo...
